### ISSUE TITLE
Is there any data that can be used to run this demo?

### ISSUE THREAD

**Issue by JayYangSS** [MichalNowicki/CalibrationCodes#1]
Would you please provide some data(eg. Calib_Results.mat, txt of imu data) so that I can run this demo?

**Comment by MichalNowicki** [comment]
It was 3 years ago - I have to ask if someone has it somewhere.

**Comment by MichalNowicki** [comment]
Link to the data: https://www.dropbox.com/sh/7sfauaek2mq89ge/AAAEANIxbrQ3WpG4aA8eSLaZa?dl=0

**Comment by JayYangSS** [comment]
Thanks!
